apiVersion: apps/v1
kind: Deployment
metadata:
  name: skijobs
  labels:
    app: skijobs
    aadpodidbinding: skijobs-podid        # why do I need this in both places?
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skijobs
  template:
    metadata:
      labels:
        app: skijobs
        aadpodidbinding: skijobs-podid        # why do I need this in both places?
    spec:
      containers:
      - name: skijobsapi
        image: {{ printf "%s%s%s" .Values.registry "/skijobsapi:v" .Values.buildNumber }}
        ports:
        - containerPort: 80
        env:
        - name: SKICONSOLE_IMAGE
          value: {{ printf "%s%s%s" .Values.registry "/skiconsole:v" .Values.buildNumber | quote }}
        - name: SUBSCRIPTIONID
          value: {{ .Values.azureSubscriptionId | quote }}
        - name: REGISTRY_NAME
          value: {{ .Values.registryName | quote }}
        - name: REGISTRY_RESOURCE_GROUP
          value: {{ .Values.registryResourceGroup | quote }}
        - name: FacebookUserIds
          value: {{ .Values.facebookUserIds | quote }}
        - name: FacebookAppId
          value: {{ .Values.facebookAppId | quote }}
        - name: ACI_CPU
          value: {{ .Values.aciCpu | quote }}
        - name: ACI_MEMORY
          value: {{ .Values.aciMemoryGb | quote }}
        - name: ACI_RESOURCEGROUP
          value: {{ .Values.aciResourceGroup | quote }}
        - name: SKIBLOBS
          value: {{ .Values.skiBlobsConnection | quote }}
        - name: GOOGLESKIVIDEOS
          value: {{ .Values.googleSkiVideosConnection | quote }}
        - name: FacebookSecret
          value: {{ .Values.facebookSecret | quote }}