apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skijobs-ingress
spec:
  rules:
  - host: {{ printf "%s%s%s" "skijobs." .Values.publicIp ".nip.io" | quote }}
    http:
      paths:
      - backend:
          serviceName: skijobs-service
          servicePort: 80
        path: /