apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skiwebapi-ingress
spec:
  rules:
  - host: {{ printf "%s%s%s" "skiwebapi." .Values.publicIp ".nip.io" | quote }}
    http:
      paths:
      - backend:
          serviceName: skiwebapi-service
          servicePort: 80
        path: /