apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapi
  labels:
    app: skiapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiwebapi
  template:
    metadata:
      labels:
        app: skiwebapi
    spec:
      containers:
      - name: skiwebapi
        image: {{ printf "%s%s%s" .Values.registry "/skiwebapi:v" .Values.buildNumber }}
        ports:
        - containerPort: 80
        env:
        - name: SUBSCRIPTIONID
          value: {{ .Values.azureSubscriptionId | quote }}
        - name: SKIJOBS_SERVICE
          value: "http://skijobs-service"
        - name: SKIBLOBS
          value: {{ .Values.skiBlobsConnection | quote }}