apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiwebapi
  labels:
    app: skiwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiwebapi
  template:
    metadata:
      labels:
        app: skiwebapi
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-key
      containers:
      - name: skiwebapi-preview
        image: gcr.io/jasondel-test-project/skiwebapi:v3.1.10
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google           
        env:
        - name: PORT
          value: "8080"
        - name: SKIBLOBS
          valueFrom:
            secretKeyRef:
              name: skiblob-secret
              key: connectionstring
        - name: SKISB
          valueFrom:
            secretKeyRef:
              name: skisb-secret
              key: connectionstring
        - name: SKISIGNALR
          valueFrom:
            secretKeyRef:
              name: skisignalr-secret
              key: connectionstring
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json                            
        - name: GOOGLE_PROJECT_ID
          value: "gke-ski"
        - name: GOOGLE_STORAGE_BUCKET
          value: "gke-ski-videos"              
        - name: Logging__LogLevel__Default
          value: "Information"
        ports:
        - containerPort: 8080

