apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiwebapi-deployment
  labels:
    app: skiwebapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skiwebapi
  template:
    metadata:
      labels:
        app: skiwebapi
    spec:
      containers:
      - name: skiwebapi
        image: wthacr.azurecr.io/skiwebapi:v2.1.2
        env:
        - name: PORT
          value: "8080"
        - name: SKIBLOBS
          valueFrom:
            secretKeyRef:
              name: skiblob-secret
              key: connectionstring
        - name: SKIJOBS_SERVICE
          value: "http://dev-ski-jobs.azurewebsites.net"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skiwebapi-service
  labels:
    app: skiwebapi
spec:
  ports:
  - port: 8080
  selector:
    app: skiwebapi
  type: ClusterIP
  
