apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiwebapi-preview
  labels:
    app: skiwebapi-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiwebapi-preview
  template:
    metadata:
      labels:
        app: skiwebapi-preview
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-key
      containers:
      - name: skiwebapi-preview
        image: gcr.io/gke-ski/skiwebapi:v2.10.1
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google        
        env:
        - name: PORT
          value: "8080"
        - name: SKIBLOBS
          valueFrom:
            secretKeyRef:
              name: skiblob-secret
              key: connectionstring
        - name: SKISB
          valueFrom:
            secretKeyRef:
              name: skisb-secret
              key: connectionstring
        - name: SKISIGNALR
          valueFrom:
            secretKeyRef:
              name: skisignalr-secret
              key: connectionstring
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json                            
        - name: GOOGLE_PROJECT_ID
          value: "gke-ski"
        - name: GOOGLE_STORAGE_BUCKET
          value: "gke-ski-videos"
        - name: Logging__LogLevel__Default
          value: "Information"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skiwebapi-service-preview
  labels:
    app: skiwebapi-preview
spec:
  ports:
  - port: 8080
  selector:
    app: skiwebapi-preview
  type: NodePort
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: skiwebapi-ingress-preview
#   annotations:
#     #nginx.ingress.kubernetes.io/enable-cors: "true"
#     # Required for debugging.
#     nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
# spec:
#   tls:
#   - hosts:
#     - jasondel.com
#     secretName: jasondel-com-tls
#   rules:
#     - host: skipreview.jasondel.com
#       http:
#         paths:
#           - backend:
#               serviceName: skiwebapi-service-preview
#               servicePort: 8080
#             path: /api
