steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: 
    - -c
    - | 
      GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=GITHUB_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d) &&
      echo "GITHUB_TOKEN=$GITHUB_TOKEN" > GITHUB_TOKEN.txt
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: 
    - -c
    - |
      VERSION=v${_TAG_NAME}.${_SHORT_SHA} &&
      IMAGE_NAME=gcr.io/$PROJECT_ID/skiconsole:${_VERSION} &&
      source GITHUB_TOKEN.txt &&
      echo 'Building ${_IMAGE_NAME}' &&
      docker build -t ${_IMAGE_NAME} &&
      --build-arg VERSION=${_VERSION} &&
      --build-arg GITHUB_TOKEN=${_GITHUB_TOKEN} &&
      -f ./SlalomTracker.Console/Dockerfile . &&
      docker push ${_IMAGE_NAME}
