steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    echo "$(gcloud secrets versions access latest --secret=GITHUB_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d)" > github_token.txt
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
  - '_GITHUB_TOKEN=$$(cat github_token.txt)'
  - '_IMAGE=gcr.io/$PROJECT_ID/skiconsole:v$TAG_NAME.$SHORT_SHA'
  - '_VERSION=$TAG_NAME'  
  args:
  - '-c'
  - |-
    echo "Printing variables"
    echo "Building $$_IMAGE with $$_GITHUB_TOKEN"
    docker build -t $$_IMAGE --build-arg VERSION=$$_VERSION --build-arg GITHUB_TOKEN=$$_GITHUB_TOKEN -f ./SlalomTracker.Console/Dockerfile .
    docker push $$_IMAGE
