steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "export GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=GITHUB_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d)" > variables.txt
    echo "export VERSION=$TAG_NAME" >> variables.txt 
    echo "export IMAGE=gcr.io/$PROJECT_ID/skiconsole:v$TAG_NAME.$SHORT_SHA" >> variables.txt 
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "Printing variables"
    cat variables.txt
    set -a
    source variables.txt
    echo "Building $IMAGE with $GITHUB_TOKEN"
    docker build -t $IMAGE --build-arg VERSION=$VERSION --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -f ./SlalomTracker.Console/Dockerfile .
    docker push $IMAGE

