steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "export _GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=GITHUB_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d)" > variables.txt
    echo "export _VERSION=$TAG_NAME" >> variables.txt 
    echo "export _IMAGE=gcr.io/$PROJECT_ID/skiconsole:v$TAG_NAME.$SHORT_SHA" >> variables.txt 
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
    - 'GITHUB_TOKEN=${_GITHUB_TOKEN}'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "Printing variables"
    cat variables.txt
    source variables.txt
    echo "Building $_IMAGE with $GITHUB_TOKEN"
    docker build -t $_IMAGE --build-arg VERSION=$_VERSION --build-arg GITHUB_TOKEN=$_GITHUB_TOKEN -f ./SlalomTracker.Console/Dockerfile .
    docker push $_IMAGE

