apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: skiprocessor-scaledobject
  namespace: ski
spec:
  scaleTargetRef:
    deploymentName: skiprocessor
  pollingInterval: 15 # seconds
  cooldownPeriod:  5 # seconds
  minReplicaCount: 0
  maxReplicaCount: 15
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: skiqueue
      connection: SKISB # This is the ENV variable in the skiprocessor deployment which has the connection string.
      queueLength: "1" 
