apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: skiprocessor-scaledobject
  namespace: ski
spec:
  scaleTargetRef:
    deploymentName: skiprocessor
  pollingInterval: 15 # seconds
  cooldownPeriod:  5 # seconds
  minReplicaCount: 0
  maxReplicaCount: 30
  triggers:
  - type: gcp-pubsub
    metadata:
      subscriptionSize: "1"
      subscriptionName: "video-uploads-subscription5"
      credentials: GOOGLE_APPLICATION_CREDENTIALS_JSON

